on: [push]
jobs:
  build:
    runs-on: codeberg-medium
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0
          filter: tree:0
          ref: ${{ github.ref }} # workaround for actions/checkout#1638
      - uses: ./.forgejo/nickeltc
        with:
          args: just build package
      - uses: forgejo/upload-artifact@v5
        with:
          name: KoboRoot.tgz
          path: KoboRoot.tgz
